import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — utxo AG",
};

export default function TermsPage() {
  return (
    <main className="px-6 py-32">
      <div className="max-w-[640px] mx-auto">
        <h1 className="text-[36px] font-extrabold tracking-[-1.5px] leading-[1.1] mb-4">
          Terms of Service
        </h1>
        <p className="text-[14px] text-[#999] mb-12">Last updated: January 30, 2026</p>

        <div className="text-[15px] text-[#555] leading-[1.75]">
          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">1. Scope and Parties</h2>
            <p>
              These Terms of Service (&ldquo;Terms&rdquo;) govern the use of all services provided by utxo AG, Dammstrasse 16, 6300 Zug, Switzerland (Handelsregister-Nummer CH-400.3.450.669-8) (&ldquo;utxo AG&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;), including but not limited to: AI agent services, email-based agent interactions, custom AI agent development, integration services, and any related software or platforms (collectively, the &ldquo;Services&rdquo;).
            </p>
            <p className="mt-3">
              By using our Services, you (&ldquo;Client&rdquo;, &ldquo;you&rdquo;) agree to be bound by these Terms. If you are using the Services on behalf of an organization, you represent that you have authority to bind that organization to these Terms.
            </p>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">2. Nature of AI Agent Services</h2>
            <p>
              Our AI agents are powered by artificial intelligence, including large language models (LLMs) and automated decision-making systems. You acknowledge and agree that:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-2">
              <li>AI agents operate autonomously based on probabilistic models and may produce incorrect, incomplete, misleading, or inappropriate outputs.</li>
              <li>AI agents are not a substitute for professional advice, including but not limited to legal, financial, medical, tax, or compliance advice.</li>
              <li>Outputs generated by AI agents do not constitute recommendations, warranties, or guarantees of any kind.</li>
              <li>You are solely responsible for reviewing, verifying, and validating any output or action taken by an AI agent before relying on it.</li>
              <li>AI agents may access, modify, or act upon data in connected systems (CRM, ERP, databases, email) as instructed. utxo AG is not liable for any consequences of such actions.</li>
            </ul>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">3. Intellectual Property</h2>

            <h3 className="text-[15px] font-semibold text-[#333] mt-4 mb-2">3.1 Our IP</h3>
            <p>
              All intellectual property rights in the Services, including but not limited to software, algorithms, models, agent architectures, workflows, prompts, system designs, documentation, and any underlying technology, remain the exclusive property of utxo AG. Nothing in these Terms transfers any intellectual property rights to you, except the limited license to use the Services as described herein.
            </p>

            <h3 className="text-[15px] font-semibold text-[#333] mt-4 mb-2">3.2 Your Data</h3>
            <p>
              You retain ownership of data you provide to our Services. However, by using our Services, you grant utxo AG a worldwide, non-exclusive, royalty-free, perpetual, irrevocable license to use, process, store, reproduce, modify, and create derivative works from any data, content, feedback, or materials you provide to or through our Services, for the purposes of: operating, maintaining, improving, and developing the Services and related technologies, including AI model training and improvement.
            </p>

            <h3 className="text-[15px] font-semibold text-[#333] mt-4 mb-2">3.3 AI-Generated Outputs</h3>
            <p>
              Outputs generated by our AI agents are provided &ldquo;as is&rdquo;. utxo AG makes no claim of ownership over outputs generated specifically for you. However, we reserve the right to use anonymized or aggregated outputs for service improvement, benchmarking, and development purposes.
            </p>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">4. Limitation of Liability</h2>
            <p className="font-semibold text-[#111]">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-2">
              <li>THE SERVICES ARE PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, RELIABILITY, OR NON-INFRINGEMENT.</li>
              <li>UTXO AG SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, DATA, BUSINESS OPPORTUNITIES, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH THE SERVICES.</li>
              <li>UTXO AG SHALL NOT BE LIABLE FOR ANY DIRECT DAMAGES EXCEEDING THE TOTAL FEES PAID BY YOU TO UTXO AG IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM.</li>
              <li>UTXO AG SHALL NOT BE LIABLE FOR ANY LOSS, DAMAGE, OR HARM RESULTING FROM: (a) errors, inaccuracies, or omissions in AI agent outputs; (b) actions taken or decisions made based on AI agent outputs; (c) unauthorized access to or alteration of your data; (d) interruption or cessation of the Services; (e) any third-party actions or integrations; (f) data loss or corruption; (g) any failure of the AI agent to perform as expected.</li>
            </ul>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">5. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless utxo AG, its directors, officers, employees, agents, and affiliates from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys&apos; fees) arising from or related to: (a) your use of the Services; (b) your breach of these Terms; (c) your violation of any applicable law; (d) any data or content you provide to the Services; (e) any actions taken by AI agents on your behalf or at your instruction; (f) any dispute between you and a third party arising from the use of the Services.
            </p>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">6. No Guarantees</h2>
            <p>We do not guarantee:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>That the Services will be uninterrupted, error-free, or available at all times</li>
              <li>That AI agent outputs will be accurate, complete, current, or suitable for any particular purpose</li>
              <li>That the Services will meet your specific requirements or expectations</li>
              <li>That any defects or errors in the Services will be corrected</li>
              <li>That the Services will be compatible with all systems, configurations, or third-party tools</li>
              <li>Any specific results, performance levels, or outcomes from using the Services</li>
            </ul>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">7. EU AI Act Compliance</h2>
            <p>
              In accordance with the EU Artificial Intelligence Act (Regulation (EU) 2024/1689), we provide the following transparency disclosures:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Our AI agents are AI systems as defined under the EU AI Act.</li>
              <li>Users interacting with our AI agents will be clearly informed that they are communicating with an AI system, not a human.</li>
              <li>We classify our AI agents as limited-risk AI systems under the EU AI Act framework.</li>
              <li>AI-generated content is clearly identified as such.</li>
              <li>We maintain documentation of our AI systems as required by applicable provisions of the EU AI Act.</li>
            </ul>
            <p className="mt-3">
              Notwithstanding these compliance measures, utxo AG disclaims all liability for any regulatory penalties, fines, or consequences arising from the Client&apos;s deployment or use of AI agents in a manner that violates the EU AI Act or any other applicable regulation. The Client is solely responsible for ensuring that their use of the Services complies with all applicable laws, including the EU AI Act.
            </p>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">8. Data Processing and GDPR</h2>
            <p>
              Data processing is governed by our <a href="/privacy" className="underline underline-offset-2 hover:text-[#111]">Privacy Policy</a>. Where we process personal data on your behalf, a separate Data Processing Agreement (DPA) may be required. You are responsible for ensuring that your use of the Services complies with GDPR and applicable data protection laws, including obtaining necessary consents from data subjects whose data is processed by AI agents.
            </p>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">9. Acceptable Use</h2>
            <p>You agree not to use the Services to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Violate any applicable law, regulation, or third-party rights</li>
              <li>Process data in violation of data protection laws</li>
              <li>Send spam, unsolicited communications, or malicious content through AI agents</li>
              <li>Attempt to reverse-engineer, decompile, or extract the underlying models, algorithms, or source code of the Services</li>
              <li>Use the Services to develop competing products or services</li>
              <li>Circumvent any security measures, access controls, or usage limits</li>
              <li>Use the Services for any illegal, fraudulent, or harmful purpose</li>
            </ul>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">10. Termination</h2>
            <p>
              We may suspend or terminate your access to the Services at any time, with or without cause, and with or without notice. Upon termination: (a) all rights granted to you under these Terms cease immediately; (b) you must cease all use of the Services; (c) we may delete your data after a reasonable retention period, unless required by law to retain it; (d) provisions that by their nature should survive termination will survive, including but not limited to Sections 3, 4, 5, 6, and 12.
            </p>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">11. Modifications</h2>
            <p>
              We reserve the right to modify these Terms at any time. Changes become effective upon publication on this website. Your continued use of the Services after any modification constitutes acceptance of the modified Terms. It is your responsibility to review these Terms periodically.
            </p>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">12. Governing Law and Jurisdiction</h2>
            <p>
              These Terms are governed by and construed in accordance with the substantive laws of Switzerland, excluding the Swiss conflict of law rules and the United Nations Convention on Contracts for the International Sale of Goods (CISG).
            </p>
            <p className="mt-3">
              Any dispute arising out of or in connection with these Terms or the Services shall be subject to the exclusive jurisdiction of the competent courts at the registered seat of utxo AG in Zug, Switzerland. utxo AG retains the right to bring proceedings in any other court of competent jurisdiction.
            </p>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">13. Severability</h2>
            <p>
              If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions shall continue in full force and effect. The invalid or unenforceable provision shall be replaced by a valid and enforceable provision that most closely achieves the intended economic purpose.
            </p>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">14. Entire Agreement</h2>
            <p>
              These Terms, together with our Privacy Policy and any applicable service agreements, constitute the entire agreement between you and utxo AG with respect to the Services and supersede all prior or contemporaneous communications, whether electronic, oral, or written.
            </p>
          </section>

          <hr className="my-8 border-[#eee]" />

          <section>
            <h2 className="text-[17px] font-bold text-[#111] mb-3">15. Contact</h2>
            <p>
              For questions about these Terms, contact:<br />
              utxo AG, Dammstrasse 16, 6300 Zug, Switzerland<br />
              <a href="mailto:business@utxo.ag" className="underline underline-offset-2 hover:text-[#111]">business@utxo.ag</a>
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-[#eee]">
          <a href="/" className="text-[13px] text-[#999] hover:text-[#111] transition-colors">
            &larr; Back to home
          </a>
        </div>
      </div>
    </main>
  );
}
